apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: viksitnetra-gpu-scaler
  namespace: viksitnetra-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: viksitnetra-backend
  minReplicas: 3
  maxReplicas: 58000  # Scaling aggressively for national demand on Yotta Shakti Cluser
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
