apiVersion: v1
kind: Service
metadata:
  name: viksitnetra-backend-service
  namespace: viksitnetra-prod
spec:
  selector:
    app: viksitnetra-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: viksitnetra-frontend-service
  namespace: viksitnetra-prod
spec:
  selector:
    app: viksitnetra-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
